mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
vue-blog:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    # 从指定头获取token
    header: Authorization
  user:
    # 用户的默认头像
    default-avatar: https://img.imgdb.cn/item/603a412e5f4313ce2536582f.jpg,https://img.imgdb.cn/item/603a412e5f4313ce25365832.jpg,https://img.imgdb.cn/item/603a412e5f4313ce25365835.jpg,https://img.imgdb.cn/item/603a412e5f4313ce25365838.jpg,https://img.imgdb.cn/item/603a412e5f4313ce2536583a.jpg,https://img.imgdb.cn/item/603a40f45f4313ce2536379e.jpg
