mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
vue-blog:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    # 从指定头获取token
    header: Authorization
  user:
    # 用户的默认头像
    default-avatar: https://s3.ax1x.com/2021/02/25/yvjDWF.jpg,https://s3.ax1x.com/2021/02/25/yvjBJU.jpg,https://s3.ax1x.com/2021/02/25/yvj0iT.jpg,https://s3.ax1x.com/2021/02/25/yvjrz4.jpg,https://s3.ax1x.com/2021/02/25/yvjdoV.jpg,https://s3.ax1x.com/2021/02/25/yvjyQJ.jpg,https://s3.ax1x.com/2021/02/25/yxpM8K.jpg,https://s3.ax1x.com/2021/02/25/yxpmU1.jpg,https://s3.ax1x.com/2021/02/25/yxpKC6.jpg,https://s3.ax1x.com/2021/02/25/yxpn4x.jpg,https://s3.ax1x.com/2021/02/25/yxpeER.jpg,https://s3.ax1x.com/2021/02/25/yxpQgO.jpg
