mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
vue-blog:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    # 从指定头获取token
    header: Authorization
  user:
    # 用户的默认头像
    default-avatar: https://image-1300566513.cos.ap-guangzhou.myqcloud.com/upload/images/5a9f48118166308daba8b6da7e466aab.jpg
